/**
 * DraftTranslationStore — słownik tłumaczeń z kluczami i18n.
 *
 * Każdy label w systemie to klucz tłumaczenia:
 *   model.Client.name.label → "Nazwa klienta" (pl) / "Client name" (en)
 *   form.fxSpot.amount.placeholder → "100 000.00"
 *   menu.dev.pagesDesigner → "Pages Designer"
 *   validation.required → "Pole wymagane" / "Field required"
 *
 * Konwencja kluczy:
 *   {context}.{entityId}.{fieldId}.{property}
 *   context: model | form | ds | page | menu | validation | action | common
 *   property: label | placeholder | description | title | subtitle | error | hint
 *
 * Storage: localStorage z prefixem `dealer-fx:i18n:`.
 */
import { Injectable, signal, computed } from '@angular/core';

export interface TranslationEntry {
  readonly key: string;
  readonly translations: Readonly<Record<string, string>>;
  readonly context?: string;
  readonly autoGenerated?: boolean;
}

export interface TranslationDictionary {
  readonly languages: ReadonlyArray<string>;
  readonly defaultLanguage: string;
  readonly entries: ReadonlyArray<TranslationEntry>;
  readonly updatedAt: number;
}

const STORAGE_KEY = 'dealer-fx:i18n:dictionary';

@Injectable({ providedIn: 'root' })
export class DraftTranslationStoreService {
  private readonly _dict = signal<TranslationDictionary>({
    languages: ['pl', 'en'],
    defaultLanguage: 'pl',
    entries: [],
    updatedAt: Date.now(),
  });

  readonly dictionary = computed(() => this._dict());
  readonly entries = computed(() => this._dict().entries);
  readonly languages = computed(() => this._dict().languages);

  constructor() {
    this.loadFromStorage();
  }

  get(key: string): TranslationEntry | null {
    return this._dict().entries.find((e) => e.key === key) ?? null;
  }

  resolve(key: string, lang?: string): string {
    const entry = this.get(key);
    if (!entry) return key;
    const l = lang ?? this._dict().defaultLanguage;
    return entry.translations[l] ?? entry.translations[this._dict().defaultLanguage] ?? key;
  }

  upsertEntry(key: string, translations: Record<string, string>, context?: string): void {
    this._dict.update((d) => {
      const existing = d.entries.findIndex((e) => e.key === key);
      const entry: TranslationEntry = { key, translations, context };
      const entries = [...d.entries];
      if (existing >= 0) {
        entries[existing] = { ...entries[existing], translations: { ...entries[existing].translations, ...translations }, context: context ?? entries[existing].context };
      } else {
        entries.push(entry);
      }
      return { ...d, entries, updatedAt: Date.now() };
    });
    this.saveToStorage();
  }

  ensureKey(key: string, defaultValue: string, context?: string): void {
    if (this.get(key)) return;
    const translations: Record<string, string> = {};
    translations[this._dict().defaultLanguage] = defaultValue;
    this.upsertEntry(key, translations, context);
  }

  removeEntry(key: string): void {
    this._dict.update((d) => ({
      ...d,
      entries: d.entries.filter((e) => e.key !== key),
      updatedAt: Date.now(),
    }));
    this.saveToStorage();
  }

  addLanguage(code: string): void {
    this._dict.update((d) => {
      if (d.languages.includes(code)) return d;
      return { ...d, languages: [...d.languages, code], updatedAt: Date.now() };
    });
    this.saveToStorage();
  }

  removeLanguage(code: string): void {
    this._dict.update((d) => ({
      ...d,
      languages: d.languages.filter((l) => l !== code),
      entries: d.entries.map((e) => {
        const { [code]: _, ...rest } = e.translations;
        return { ...e, translations: rest };
      }),
      updatedAt: Date.now(),
    }));
    this.saveToStorage();
  }

  setDefaultLanguage(code: string): void {
    this._dict.update((d) => ({ ...d, defaultLanguage: code, updatedAt: Date.now() }));
    this.saveToStorage();
  }

  bulkEnsureKeys(keys: ReadonlyArray<{ key: string; defaultValue: string; context?: string }>): void {
    let changed = false;
    this._dict.update((d) => {
      const entries = [...d.entries];
      const existingKeys = new Set(entries.map((e) => e.key));
      for (const k of keys) {
        if (existingKeys.has(k.key)) continue;
        const translations: Record<string, string> = {};
        translations[d.defaultLanguage] = k.defaultValue;
        entries.push({ key: k.key, translations, context: k.context, autoGenerated: true });
        changed = true;
      }
      return changed ? { ...d, entries, updatedAt: Date.now() } : d;
    });
    if (changed) this.saveToStorage();
  }

  private loadFromStorage(): void {
    if (typeof window === 'undefined' || !window.localStorage) return;
    try {
      const raw = window.localStorage.getItem(STORAGE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw) as TranslationDictionary;
        if (parsed && Array.isArray(parsed.entries)) this._dict.set(parsed);
      }
    } catch { /* skip */ }
  }

  private saveToStorage(): void {
    if (typeof window === 'undefined' || !window.localStorage) return;
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(this._dict()));
  }
}

export function generateI18nKey(context: string, entityId: string, fieldId?: string, property = 'label'): string {
  return fieldId ? `${context}.${entityId}.${fieldId}.${property}` : `${context}.${entityId}.${property}`;
}
