/**
 * fx-translation-manager — zarządzanie słownikiem tłumaczeń.
 *
 * Wszystkie labele w systemie to klucze i18n. Ten designer:
 *  - lista wszystkich kluczy z filtrami po kontekście (model/form/ds/page/menu)
 *  - edycja tłumaczeń per język (kolumny: klucz | pl | en | de | ...)
 *  - dodawanie/usuwanie języków
 *  - auto-generated keys (z Model/Form/DS designerów) oznaczone tagiem
 *  - brakujące tłumaczenia podświetlone
 *  - export słownika (JSON per language)
 */
import { computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { EchelonWidget } from '@echelon-framework/runtime';
import { DraftTranslationStoreService, type TranslationEntry } from './draft-translation-store';

const CONTEXTS = ['all', 'model', 'form', 'ds', 'page', 'menu', 'validation', 'action', 'common'] as const;

@EchelonWidget({
  manifest: {
    type: 'translation-manager',
    version: '1.0.0',
    category: 'designer',
    description: 'Zarządzanie słownikiem tłumaczeń i18n — klucze, języki, braki.',
    inputs: [],
    outputs: [],
    actions: [],
    capabilities: {},
    testability: { interactions: [], observables: ['translation-manager'], lifecycleGates: ['ready'] },
  },
  selector: 'fx-translation-manager',
  imports: [CommonModule, FormsModule],
  template: `
    <div class="wrap" data-testid="translation-manager" data-echelon-state="ready">
      <div class="toolbar">
        <h2>🌐 Tłumaczenia</h2>
        <div class="meta">
          <span>{{ i18n.entries().length }} kluczy</span>
          <span class="sep">·</span>
          <span>{{ i18n.languages().length }} języków</span>
          <span class="sep">·</span>
          <span class="missing">{{ missingCount() }} brakujących</span>
        </div>
        <div class="toolbar-actions">
          <select class="ctx-filter" [ngModel]="contextFilter()" (ngModelChange)="contextFilter.set($event)">
            @for (c of contexts; track c) { <option [value]="c">{{ c === 'all' ? 'Wszystkie' : c }}</option> }
          </select>
          <input type="search" class="search" placeholder="Szukaj klucz..."
                 [ngModel]="filter()" (ngModelChange)="filter.set($event)" />
          <button type="button" class="btn-add" (click)="addEntry()">+ Klucz</button>
          <button type="button" class="btn-lang" (click)="addLanguagePrompt()">+ Język</button>
          <button type="button" class="btn-export" (click)="exportAll()">📤 Export</button>
        </div>
      </div>

      <div class="lang-bar">
        <span class="lang-label">Języki:</span>
        @for (lang of i18n.languages(); track lang) {
          <span class="lang-tag" [class.default]="lang === i18n.dictionary().defaultLanguage">
            {{ lang }}
            @if (lang === i18n.dictionary().defaultLanguage) { <span class="default-badge">default</span> }
            @else {
              <button type="button" class="lang-set-default" (click)="i18n.setDefaultLanguage(lang)" title="Ustaw jako domyślny">★</button>
              <button type="button" class="lang-rm" (click)="i18n.removeLanguage(lang)" title="Usuń język">✕</button>
            }
          </span>
        }
      </div>

      <div class="table-wrap">
        <div class="table-header">
          <span class="col-key">Klucz</span>
          <span class="col-ctx">Kontekst</span>
          @for (lang of i18n.languages(); track lang) {
            <span class="col-lang">{{ lang }}</span>
          }
          <span class="col-actions"></span>
        </div>
        @for (entry of filteredEntries(); track entry.key) {
          <div class="table-row" [class.has-missing]="hasMissing(entry)" [class.auto]="entry.autoGenerated">
            <input type="text" class="cell-key" [value]="entry.key" disabled />
            <span class="cell-ctx">{{ entry.context ?? '—' }}</span>
            @for (lang of i18n.languages(); track lang) {
              <input type="text" class="cell-lang" [class.empty]="!entry.translations[lang]"
                     [value]="entry.translations[lang] ?? ''"
                     (change)="updateTranslation(entry.key, lang, $any($event.target).value)"
                     [placeholder]="'(' + lang + ')'" />
            }
            <div class="cell-actions">
              @if (entry.autoGenerated) { <span class="auto-tag">auto</span> }
              <button type="button" class="btn-rm" (click)="i18n.removeEntry(entry.key)">✕</button>
            </div>
          </div>
        }
        @if (filteredEntries().length === 0) {
          <div class="empty">
            @if (filter() || contextFilter() !== 'all') {
              Brak wyników dla aktualnych filtrów
            } @else {
              Brak kluczy tłumaczeń. Twórz modele/formularze — klucze generują się automatycznie.
              Lub dodaj ręcznie kliknięciem "+ Klucz".
            }
          </div>
        }
      </div>

      @if (exportedContent()) {
        <div class="export-section">
          <div class="export-header">
            <span>Export JSON</span>
            <button type="button" class="btn-copy" (click)="copyExport()">{{ copied() ? '✓' : '📋' }} Kopiuj</button>
            <button type="button" class="btn-close" (click)="exportedContent.set(null)">✕</button>
          </div>
          <pre class="export-code">{{ exportedContent() }}</pre>
        </div>
      }
    </div>
  `,
  styles: [`
    :host { display: block; padding: 16px; color: var(--ech-fg, #e5e7eb); height: 100%; }
    .wrap { display: flex; flex-direction: column; height: 100%; background: var(--ech-panel, #0f172a); border: 1px solid var(--ech-border, #1f2937); border-radius: 6px; }

    .toolbar { display: flex; align-items: center; gap: 12px; padding: 12px 16px; border-bottom: 1px solid var(--ech-border, #1f2937); flex-wrap: wrap; }
    .toolbar h2 { margin: 0; font-size: 15px; font-weight: 600; color: var(--ech-accent, #58a6ff); }
    .meta { display: flex; align-items: center; gap: 8px; font-size: 12px; color: var(--ech-muted, #9ca3af); }
    .sep { color: var(--ech-muted, #6b7280); }
    .missing { color: #fca5a5; }
    .toolbar-actions { display: flex; gap: 6px; margin-left: auto; align-items: center; }
    .ctx-filter { padding: 5px 8px; background: var(--ech-panel-alt, #1f2937); border: 1px solid var(--ech-border, #374151); color: var(--ech-fg, #e5e7eb); border-radius: 3px; font-size: 11px; }
    .search { padding: 5px 8px; background: var(--ech-panel-alt, #1f2937); border: 1px solid var(--ech-border, #374151); color: var(--ech-fg, #e5e7eb); border-radius: 3px; font-size: 11px; width: 180px; }
    .btn-add, .btn-lang { padding: 4px 10px; background: #064e3b; border: 1px solid #10b981; color: #d1fae5; border-radius: 2px; font-size: 11px; cursor: pointer; font-family: inherit; }
    .btn-lang { background: #1e3a5f; border-color: #3b82f6; color: #e0f2fe; }
    .btn-export { padding: 4px 10px; background: #78350f; border: 1px solid #f59e0b; color: #fef3c7; border-radius: 2px; font-size: 11px; cursor: pointer; font-family: inherit; }

    .lang-bar { display: flex; align-items: center; gap: 6px; padding: 8px 16px; border-bottom: 1px solid var(--ech-border, #1f2937); background: var(--ech-panel-alt, #111827); }
    .lang-label { font-size: 10px; color: var(--ech-muted, #9ca3af); text-transform: uppercase; letter-spacing: 0.3px; font-weight: 600; }
    .lang-tag { display: inline-flex; align-items: center; gap: 4px; padding: 2px 8px; background: #1f2937; border-radius: 3px; font-size: 11px; font-weight: 600; color: var(--ech-fg, #e5e7eb); }
    .lang-tag.default { border: 1px solid #3b82f6; color: #93c5fd; }
    .default-badge { font-size: 8px; color: #3b82f6; text-transform: uppercase; }
    .lang-set-default { background: transparent; border: none; color: var(--ech-muted, #6b7280); cursor: pointer; font-size: 10px; padding: 0 2px; }
    .lang-set-default:hover { color: #fcd34d; }
    .lang-rm { background: transparent; border: none; color: #fca5a5; cursor: pointer; font-size: 10px; padding: 0 2px; }

    .table-wrap { flex: 1; overflow: auto; }
    .table-header { display: flex; gap: 4px; padding: 8px 12px; background: #1f2937; font-size: 9px; text-transform: uppercase; letter-spacing: 0.3px; color: var(--ech-muted, #6b7280); font-weight: 600; position: sticky; top: 0; z-index: 1; }
    .col-key { flex: 2.5; }
    .col-ctx { flex: 0.8; }
    .col-lang { flex: 1.5; }
    .col-actions { width: 60px; }

    .table-row { display: flex; gap: 4px; padding: 4px 12px; border-bottom: 1px solid var(--ech-border, #0f172a); align-items: center; }
    .table-row:hover { background: #1f293722; }
    .table-row.has-missing { background: #7f1d1d0d; }
    .table-row.auto { border-left: 2px solid #6b728033; }
    .cell-key { flex: 2.5; padding: 3px 6px; background: transparent; border: 1px solid transparent; color: #93c5fd; font-size: 10px; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
    .cell-ctx { flex: 0.8; font-size: 9px; color: var(--ech-muted, #6b7280); text-transform: uppercase; }
    .cell-lang { flex: 1.5; padding: 3px 6px; background: var(--ech-panel-alt, #1f2937); border: 1px solid var(--ech-border, #374151); color: var(--ech-fg, #e5e7eb); border-radius: 2px; font-size: 11px; font-family: inherit; }
    .cell-lang.empty { border-color: #ef444444; background: #7f1d1d11; }
    .cell-actions { width: 60px; display: flex; align-items: center; gap: 4px; justify-content: flex-end; }
    .auto-tag { font-size: 8px; color: var(--ech-muted, #6b7280); background: #1f2937; padding: 1px 4px; border-radius: 2px; }
    .btn-rm { background: transparent; border: 1px solid #7f1d1d44; color: #fca5a5; width: 18px; height: 18px; border-radius: 2px; cursor: pointer; font-size: 10px; display: flex; align-items: center; justify-content: center; padding: 0; }
    .btn-close { background: transparent; border: none; color: var(--ech-muted, #9ca3af); cursor: pointer; font-size: 14px; padding: 2px 6px; }

    .empty { padding: 30px; text-align: center; font-size: 12px; color: var(--ech-muted, #6b7280); font-style: italic; }

    .export-section { margin: 12px; background: var(--ech-panel-alt, #111827); border: 1px solid var(--ech-border, #1f2937); border-radius: 4px; }
    .export-header { display: flex; align-items: center; gap: 8px; padding: 6px 10px; border-bottom: 1px solid var(--ech-border, #1f2937); font-size: 10px; color: var(--ech-muted, #9ca3af); font-weight: 600; text-transform: uppercase; }
    .btn-copy { padding: 2px 8px; background: #1e3a5f; border: 1px solid #3b82f6; color: #e0f2fe; border-radius: 2px; font-size: 10px; cursor: pointer; font-family: inherit; margin-left: auto; }
    .export-code { margin: 0; padding: 10px; font-size: 10px; color: #d1d5db; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; overflow: auto; max-height: 200px; white-space: pre; }
  `],
})
export class TranslationManagerComponent {
  readonly i18n = inject(DraftTranslationStoreService);

  readonly contexts = CONTEXTS;
  readonly filter = signal('');
  readonly contextFilter = signal<string>('all');
  readonly exportedContent = signal<string | null>(null);
  readonly copied = signal(false);

  readonly filteredEntries = computed<ReadonlyArray<TranslationEntry>>(() => {
    let entries = this.i18n.entries();
    const ctx = this.contextFilter();
    if (ctx !== 'all') entries = entries.filter((e) => e.context === ctx);
    const q = this.filter().trim().toLowerCase();
    if (q) entries = entries.filter((e) =>
      e.key.toLowerCase().includes(q) ||
      Object.values(e.translations).some((v) => v.toLowerCase().includes(q)));
    return entries;
  });

  readonly missingCount = computed<number>(() => {
    const langs = this.i18n.languages();
    return this.i18n.entries().reduce((sum, e) =>
      sum + langs.filter((l) => !e.translations[l]).length, 0);
  });

  hasMissing(entry: TranslationEntry): boolean {
    return this.i18n.languages().some((l) => !entry.translations[l]);
  }

  updateTranslation(key: string, lang: string, value: string): void {
    this.i18n.upsertEntry(key, { [lang]: value });
  }

  addEntry(): void {
    const key = prompt('Klucz tłumaczenia (np. form.fxSpot.amount.label):');
    if (!key) return;
    const defaultValue = prompt(`Wartość domyślna (${this.i18n.dictionary().defaultLanguage}):`) ?? key;
    const ctx = key.split('.')[0] ?? 'common';
    this.i18n.ensureKey(key, defaultValue, ctx);
  }

  addLanguagePrompt(): void {
    const code = prompt('Kod języka (np. en, de, fr, es):');
    if (code) this.i18n.addLanguage(code.toLowerCase().trim());
  }

  exportAll(): void {
    const dict = this.i18n.dictionary();
    const result: Record<string, Record<string, string>> = {};
    for (const lang of dict.languages) {
      result[lang] = {};
      for (const e of dict.entries) {
        if (e.translations[lang]) result[lang][e.key] = e.translations[lang];
      }
    }
    this.exportedContent.set(JSON.stringify(result, null, 2));
    this.copied.set(false);
  }

  copyExport(): void {
    const content = this.exportedContent();
    if (!content) return;
    navigator.clipboard.writeText(content).then(() => {
      this.copied.set(true);
      setTimeout(() => this.copied.set(false), 2000);
    });
  }
}
