/**
 * Position Close + CSV Export — flow dealera na /positions.
 *
 * Realny przebieg aktualnie w kodzie:
 *  - user widzi blotter z otwartymi pozycjami,
 *  - live spotUsdPln (random-walk simulator) aktualizuje mark,
 *  - computed totalPnl na żywo liczy sumę P&L,
 *  - user może zamknąć pozycję (event) lub wyeksportować blotter do CSV.
 */
import type { BusinessProcess } from './types.js';

export const positionCloseProcess: BusinessProcess = {
  id: 'position-close',
  title: 'Position Close + CSV Export — /positions',
  description: 'Dealer monitoruje otwarte pozycje, live spot aktualizuje mark i P&L, zamyka wybraną pozycję albo eksportuje blotter do CSV dla compliance.',
  entryRoute: '/positions',
  lanes: [
    { id: 'dealer',     label: 'Dealer FX',    color: '#10b981' },
    { id: 'system',     label: 'System',       color: '#f59e0b' },
    { id: 'backoffice', label: 'Back-office',  color: '#ec4899' },
    { id: 'compliance', label: 'Compliance',   color: '#a78bfa' },
  ],
  steps: [
    {
      id: 'p1',
      lane: 'dealer',
      kind: 'start',
      label: '1. Dealer otwiera blotter',
      description: 'Strona /positions renderuje layout z title + totals + candlestick chart + blotter.',
      status: 'implemented',
      impl: { page: 'positions', route: '/positions', file: 'src/app/pages/positions.page.ts' },
      howToSee: 'Menu → Transakcje → Historia (lub /positions).',
    },
    {
      id: 'p2',
      lane: 'system',
      kind: 'event',
      label: '2. Stream spotUsdPln (random-walk simulator)',
      description: 'Simulator wysyła co 600ms nową wartość spot. DataBus emituje do wszystkich subskrybentów.',
      status: 'implemented',
      impl: {
        datasource: 'spotUsdPln',
        file: 'src/app/datasources/spot-usd-pln.ds.ts',
        note: 'W prod wymieniasz simulator na WS endpoint — zero zmian w page config.',
      },
      howToSee: 'Wartości w kolumnie Mark blottera aktualizują się co ~600ms.',
    },
    {
      id: 'p3',
      lane: 'system',
      kind: 'script',
      label: '3. computed: positionsTotalPnl',
      description: 'PureFunction dostaje (positions, spot) i zwraca sum(quantity*spot - costBase). Auto-recompute przy zmianie dowolnego inputu.',
      status: 'implemented',
      impl: {
        computed: 'positionsTotalPnl',
        file: 'src/app/functions/positions-total-pnl.ts',
      },
      howToSee: 'Stat-tile "Total P&L (live)" odświeża się przy każdym tick simulatora spot.',
    },
    {
      id: 'p4',
      lane: 'dealer',
      kind: 'task',
      label: '4. Wykres P&L (candlestick, feature-flag gated)',
      description: 'Widget candlestick-chart pobiera pnlHistory DS. Programowy gate przez isFeatureFlagAllowed("candlestick-chart") — jak flaga off, widget pokazuje 🔒 placeholder.',
      status: 'implemented',
      impl: {
        widget: 'candlestick-chart',
        datasource: 'pnlHistory',
        file: 'src/app/widgets/candlestick-chart.component.ts',
        note: 'Fallback SVG (bez ECharts). Dla full chart dodaj <script src="echarts.min.js"> do index.html.',
      },
      howToSee: 'Środkowo-prawy obszar /positions. Rola "dealer" ma flagę on → widzisz chart. Zmień feature flag żeby zobaczyć gated state.',
    },
    {
      id: 'p5',
      lane: 'dealer',
      kind: 'task',
      label: '5. Zamknięcie pozycji — klik "Close"',
      description: 'Blotter emituje "blotter.closeRequest" z payloadem pozycji. Handler w page configu emituje dalej "fx.position.closed".',
      status: 'partial',
      impl: {
        widget: 'positions-blotter',
        event: 'blotter.closeRequest',
        handler: 'blotter.closeRequest',
        file: 'src/app/pages/positions.page.ts',
        note: 'Handler emituje event, ale brak kroku side-effect (brak POST do backendu). Cache invalidateOn="fx.position.closed" zadziała po rc.16.',
      },
      howToSee: 'Klik przycisku Close w wierszu blottera → w console log zobaczysz event (EventBus debug).',
    },
    {
      id: 'p6',
      lane: 'compliance',
      kind: 'event',
      label: '6. Compliance snapshot (audit trail)',
      description: 'Framework ma audit kontrakt — każdy close powinien dołączyć snapshot (hash rules + timestamp). TODO dla zespołu compliance.',
      status: 'todo',
      impl: {
        note: 'Kontrakt w @echelon-framework/core/audit istnieje, projekt nie ma jeszcze implementacji dla close-flow.',
        file: 'node_modules/@echelon-framework/core/dist/audit/index.d.ts',
      },
    },
    {
      id: 'p7',
      lane: 'dealer',
      kind: 'task',
      label: '7. Export CSV — akcja "exportCsv"',
      description: 'Widget positions-blotter emituje "positions.exportCsv" z payloadem $ds.positionsList. Handler w configu emituje "fx.positions.csv.download-requested".',
      status: 'implemented',
      impl: {
        widget: 'positions-blotter',
        event: 'positions.exportCsv',
        handler: 'positions.exportCsv',
        file: 'src/app/pages/positions.page.ts',
        note: 'Handler tylko emituje event — side-effect download w app.component.ts.',
      },
      howToSee: 'Kliknij przycisk "Export CSV" w górnym pasku blottera.',
    },
    {
      id: 'p8',
      lane: 'system',
      kind: 'script',
      label: '8. exportPositionsToCsv — encodeCsv + downloadCsv',
      description: 'AppComponent subskrybuje EventBus, przy zdarzeniu wywołuje exportPositionsToCsv() z framework-integrations. Kolumny: Kod / Para / Wolumen / Cena wejścia / P&L / Otwarta. RFC 4180 + BOM + ;-delimiter dla Excela.',
      status: 'implemented',
      impl: {
        event: 'fx.positions.csv.download-requested',
        file: 'src/app/bootstrap/framework-integrations.ts',
        note: 'Używa @echelon-framework/export-core (encodeCsv + downloadCsv). Metryka export.csv w telemetry.',
      },
      howToSee: 'Po kliknięciu CSV przeglądarka pobiera positions-YYYY-MM-DD.csv. Otwórz w Excelu — BOM pozwala na poprawne kodowanie PL.',
    },
    {
      id: 'p9',
      lane: 'backoffice',
      kind: 'end',
      label: '9. Backoffice dostaje archiwum',
      description: 'Plik ląduje u user-a. Dalsza dystrybucja (email/shared drive) poza zakresem.',
      status: 'partial',
      impl: { note: 'Scheduled reports + email delivery — future roadmap (nie ma w rc.15).' },
    },
  ],
  edges: [
    { from: 'p1', to: 'p2' },
    { from: 'p2', to: 'p3' },
    { from: 'p3', to: 'p4' },
    { from: 'p4', to: 'p5', label: 'live monitoring' },
    { from: 'p5', to: 'p6' },
    { from: 'p6', to: 'p3', label: 'refresh totals' },
    { from: 'p4', to: 'p7', label: 'eksport' },
    { from: 'p7', to: 'p8' },
    { from: 'p8', to: 'p9' },
  ],
};
